### PR TITLE
First implementation of WebGL support

### PR DESCRIPTION
**Pull request by AstrorEnales**
This is a first working implementation of webgl.
The CanvasElement got an extra overload of GetContext for attributes (like antialias, etc. for opengl)

All classes in WebGL namespace and the CanvasContextWebGL class are directly parsed from the webgl spec.
see https://www.khronos.org/registry/webgl/specs/latest/webgl.idl

### CODE REVIEW

**Comment by erik-kallen** [comment]
Nice. Thank you for your support of the project.

A few comments though

1) For consistency with the rest of all libraries, members should be PascalCased (but I can fix this).
2) How does the CanvasContextWebGL work? How are the constants accessed? (I'm not saying you're wrong here, just that I don't know WebGL)
3) I can't find (with a quick google) what the attributes in your GetContext() overload can be. Is it not possible to create an [Imported, Serializable] class with all options? Is this where the WebGLContextAttributes class comes in?
4) Are ArrayBuffer, ArrayBufferView, Float32Array and Int32Array specific to WebGL? If not, I think they should be somewhere else, potentially even inside mscorlib.
5) WebGLActiveInfom, WebGLShaderPrecisionFormat I think should be [Serializable]. If it is, we can also add a constructor to it (which will be treated as an inline object initializer).
6) I am not 100% clear on the usage of the WebGLContextAttributes class. This should probably be an [Imported, Serializable] class, with the Get() method replaced with a constructor
7) Please don't reformat entire files (Web.csproj)

**Comment by AstrorEnales** [comment]
Thanks for the feedback.

1) Will be fixed asap
2) The webgl context is just like the CanvasContext2D returned by Canvas.GetContext when using the parameter "webgl" or "webgl-experimental".
An example call for the methods is "vShader = gl.createShader(gl.VERTEX_SHADER);"
gl is the returned CanvasContextWebGL and the constants are like enum values, but opengl is always like this with having all constants in the context instance.
3) The attributes are a set of settings for webgl to activate/deactivate stencil/depth/antialias etc.
Example is:
var attributes = WebGLContextAttributes.Get(true, true, false, true, true, false);
gl = (CanvasContextWebGL)canvas.GetContext("webgl", attributes);
It should be possible to introduce a class there, but it was faster for now to use the dictionary as a first implementation.
4) These types are also in a specification from the khronos group, and originated in the WebGL specification.
see http://www.khronos.org/registry/typedarray/specs/latest/typedarray.idl
5) I'll take a look at that...
6) Same as 3.
7) Oh, VS2012 changed that, i'll take a look at that, too.

**Comment by erik-kallen** [comment]
3, 6:
A better implementation then is:

```
public CanvasContext GetContext(string contextID, WebGLContextAttributes attributes) {
    return null;
}

[Imported, Serializable]
public class WebGLContextAttributes {
    public bool Alpha { get; set; }
    public bool Depth { get; set; }
    public bool Stencil { get; set; }
    public bool Antialias { get; set; }
    public bool PremultipliedAlpha { get; set; }
    public bool PreserveDrawingBuffer { get; set; }

    public WebGLContextAttributes(bool alpha, bool depth, bool stencil, bool antialias, bool premultipliedAlpha, bool preserveDrawingBuffer) {
    }
}
```

**Comment by erik-kallen** [comment]
You don't need the [ScriptName]s, the compiler will camelCase everything automatically (as long as your assembly doesn't have a [PreserveMemberCase] attribute (which the web assembly doesn't)

**Comment by AstrorEnales** [comment]
I changed back the formatting of the Web.csproj.
5) These are only types that are returned by methods and never created by hand, so i changed them to interfaces, like i also did with Texture, Shader, Program, etc. They're never created by hand.

I also added some documentation to most classes.

**Comment by erik-kallen** [comment]
This won't work for the data types. The properties will be treated as being implemented with get/set methods (you cannot, at least currently, specify [IntrinsicProperty] on interface properties).

**Pull request merged**
